### ISSUE TITLE
Failure on Import the NodeSource GPG key into apt

### ISSUE THREAD

**Issue by trigoesrodrigo** [d-cent/objective8#10]
Deploying on Ubuntu 14.04 is now impossible as the nodesource gpg can't be imported because default python version doesn't support sni. 

This is exactly what's described in https://github.com/nodesource/ansible-nodejs-role/issues/33

There there are several solutions proposed. The easiest one is to replace the `add nodesource apt-key` task in the dev role for:

```
- name: Import the NodeSource GPG key into apt
  apt_key:
   id: 68576280
   url: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"   
```
